In [1]:
import tensorflow as tf

In [3]:
dropout = tf.placeholder(tf.float32)
W = tf.Variable(tf.ones([10, 10]))
W_d = tf.nn.dropout(x, dropout)

sess = tf.Session()
sess.run(tf.global_variables_initializer())

print(sess.run(W_d, feed_dict={dropout: 0.4}))

[[ 2.5  2.5  2.5  2.5  0.   0.   2.5  2.5  2.5  0. ]
 [ 0.   0.   0.   0.   2.5  0.   2.5  0.   0.   2.5]
 [ 0.   0.   0.   2.5  2.5  2.5  2.5  2.5  0.   0. ]
 [ 2.5  2.5  0.   0.   2.5  2.5  2.5  2.5  0.   0. ]
 [ 0.   2.5  0.   0.   0.   0.   0.   0.   0.   2.5]
 [ 0.   0.   0.   0.   2.5  2.5  0.   2.5  2.5  2.5]
 [ 2.5  2.5  2.5  0.   2.5  2.5  0.   0.   2.5  0. ]
 [ 0.   0.   2.5  2.5  0.   2.5  0.   0.   2.5  2.5]
 [ 2.5  2.5  0.   2.5  2.5  2.5  0.   0.   0.   0. ]
 [ 0.   0.   0.   0.   2.5  0.   2.5  0.   2.5  0. ]]
